### ISSUE TITLE
Live demo not available

### ISSUE THREAD

**Issue by spatialhast** [PropellerAero/cesium-elevation-gradient#6]
Live demo (https://propelleraero.github.io/cesium-elevation-gradient/) not available
![image](https://user-images.githubusercontent.com/3269617/37659916-d98dd152-2c59-11e8-8acf-ae95464492f3.png)

**Comment by chris-cooper** [comment]
I've removed the live example and included a link to Cesium's built in support for elevation gradients and contours.
