### ISSUE TITLE
Run test app with local server

### ISSUE THREAD

**Issue by spatialhast** [PropellerAero/cesium-elevation-gradient#7]
I use next steps to build 'cesium-elevation-gradient' web app:
```
$ npm install
$ npm install --save cesium
$ npm install --save-dev webpack-cli
$ npm install --save-dev webpack-dev-server
$ npm install --save-dev shader-loader
```
When I run `$ npm start` ("start": "webpack-dev-server --progress --display-error-details") I receive error:
![image](https://user-images.githubusercontent.com/3269617/37666428-306e1c58-2c68-11e8-909d-ce93dba8ff64.png)

**Comment by chris-cooper** [comment]
I've updated the example app. Please try again.
